const SUCCESS = '0';
const REQUEST_PARAMS_INVALID = '100001';
const USER_ALREADY_EXIST = '100002';
const TOKEN_INVALID = '100003';

module.exports = {
    SUCCESS,
    REQUEST_PARAMS_INVALID,
    USER_ALREADY_EXIST,
    TOKEN_INVALID,
};
