const SUCCESS = '0';
const REQUEST_PARAMS_INVALID = '100001';
const USER_ALREADY_EXIST = '100002';
const TOKEN_INVALID = '100003';
const HAVE_NO_RIGHT = '100004';
const RESOURCE_NOT_EXIST = '100005';
const SERVER_ERROR = '100006';
const RESOURCE_EXIST = '100007';
const USERNAME_OR_EMAIL_INVALID = '100008';

module.exports = {
    SUCCESS,
    REQUEST_PARAMS_INVALID,
    USER_ALREADY_EXIST,
    TOKEN_INVALID,
    HAVE_NO_RIGHT,
    RESOURCE_NOT_EXIST,
    SERVER_ERROR,
    RESOURCE_EXIST,
    USERNAME_OR_EMAIL_INVALID,
};
